name: Coding Standards

on:
    push:
        branches:
            - develop
            - stable
            - release/**
    pull_request:
        branches:
            - develop

jobs:
    lint:
        name: Script and Style Coding Standards
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            - name: Install NodeJS
              uses: actions/setup-node@v3
              with:
                  node-version-file: '.nvmrc'
                  cache: npm
            - name: NPM install
              run: npm install

            - name: Run eslint
              run: npm run lint:js
            - name: Run stylelint
              run: npm run lint:style
            - name: Run npmPkgJsonLint
              run: npm run lint:pkg
            - name: Run markdownlint
              run: npm run lint:docs
    phpcs:
        name: PHP Coding Standards
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            - name: Set up PHP version
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '7.4'
                  coverage: none
                  tools: composer, cs2pr
            - name: Log debug information
              run: |
                  php --version
                  composer --version
            - name: Install Composer dependencies
              uses: ramsey/composer-install@v2
              with:
                  composer-options: '--no-progress --no-ansi --no-interaction'
            - name: Make Composer packages available globally
              run: echo "${PWD}/vendor/bin" >> $GITHUB_PATH
            - name: Log PHPCS debug information
              run: phpcs -i
            - name: Run PHPCS
              run: phpcs -q -n --report=checkstyle . | cs2pr
