name: Static Analysis (Linting, etc.)

on:
    pull_request:
    push:
        branches:
            - develop
            - stable
            - release/**
    workflow_dispatch:

jobs:
    check:
        name: Lint
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Use stored Node.js version
              uses: actions/setup-node@v4
              with:
                  node-version-file: '.nvmrc'
                  check-latest: true
                  cache: npm

            - name: Npm install
              run: npm install

            - name: Lint JavaScript
              run: npm run lint:js

            - name: Lint Styles
              run: npm run lint:style

            - name: Lint package.json
              run: npm run lint:pkg

            - name: Lint Docs
              run: npm run lint:docs

    phpcs:
        name: PHP Coding Standards
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Set up PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.2'
                  coverage: none
                  tools: composer, cs2pr

            - name: Install Composer dependencies
              uses: ramsey/composer-install@v3
              with:
                  custom-cache-suffix: $(date -u "+%Y-%m")

            - name: Make Composer packages available globally
              run: echo "${PWD}/vendor/bin" >> $GITHUB_PATH

            - name: Run PHPCS checks
              id: phpcs
              run: phpcs -q -n --report=checkstyle . | cs2pr
